# 1. Kết nối DB dùng biến môi trường (Hợp lệ để push GitHub)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Biến STATION_ID
station.id=${STATION_ID:1}