# Kết nối tới Aiven (Thay Host và Password của bạn vào)
spring.datasource.url=jdbc:mysql://mysql-367a4e40-abcdxyz.j.aivencloud.com:11756/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_psOYeLPSKO75q_-OfHD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Biến STATION_ID để phân biệt 5 trạm (Mặc định là 1 nếu chạy local)
station.id=${STATION_ID:1}